// flow-typed signature: db97acca8cbccb87d3bb5cc809abfb63
// flow-typed version: <<STUB>>/fromnow_v3.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fromnow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fromnow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fromnow/dist/fromnow' {
  declare module.exports: any;
}

declare module 'fromnow/dist/fromnow.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fromnow/dist/fromnow.js' {
  declare module.exports: $Exports<'fromnow/dist/fromnow'>;
}
declare module 'fromnow/dist/fromnow.min.js' {
  declare module.exports: $Exports<'fromnow/dist/fromnow.min'>;
}
