// flow-typed signature: 890e41d67199ee23e33d4ad3ccb7b307
// flow-typed version: <<STUB>>/obj-str_v1.0.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'obj-str'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'obj-str' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'obj-str/dist/obj-str' {
  declare module.exports: any;
}

declare module 'obj-str/dist/obj-str.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'obj-str/dist/obj-str.js' {
  declare module.exports: $Exports<'obj-str/dist/obj-str'>;
}
declare module 'obj-str/dist/obj-str.min.js' {
  declare module.exports: $Exports<'obj-str/dist/obj-str.min'>;
}
