// flow-typed signature: 76b142d70cebfa3147c13ecd8e2a19c9
// flow-typed version: <<STUB>>/sinuous_v0.27.0-beta.4/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinuous'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinuous' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sinuous/all/src/all' {
  declare module.exports: any;
}

declare module 'sinuous/all/src' {
  declare module.exports: any;
}

declare module 'sinuous/babel-plugin-htm/src' {
  declare module.exports: any;
}

declare module 'sinuous/data/src/data' {
  declare module.exports: any;
}

declare module 'sinuous/dist/all' {
  declare module.exports: any;
}

declare module 'sinuous/dist/all.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/babel-plugin-htm' {
  declare module.exports: any;
}

declare module 'sinuous/dist/data' {
  declare module.exports: any;
}

declare module 'sinuous/dist/data.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/h' {
  declare module.exports: any;
}

declare module 'sinuous/dist/h.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/htm' {
  declare module.exports: any;
}

declare module 'sinuous/dist/htm.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/hydrate' {
  declare module.exports: any;
}

declare module 'sinuous/dist/hydrate.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/map' {
  declare module.exports: any;
}

declare module 'sinuous/dist/map.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/map/mini' {
  declare module.exports: any;
}

declare module 'sinuous/dist/map/mini.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/memo' {
  declare module.exports: any;
}

declare module 'sinuous/dist/memo.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/observable' {
  declare module.exports: any;
}

declare module 'sinuous/dist/observable.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/render' {
  declare module.exports: any;
}

declare module 'sinuous/dist/render.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/sinuous-observable.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/sinuous' {
  declare module.exports: any;
}

declare module 'sinuous/dist/sinuous.min' {
  declare module.exports: any;
}

declare module 'sinuous/dist/template' {
  declare module.exports: any;
}

declare module 'sinuous/dist/template.min' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/add' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/api' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/cast-node' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/constants' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/frag' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/h' {
  declare module.exports: any;
}

declare module 'sinuous/h/src' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/insert' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/property' {
  declare module.exports: any;
}

declare module 'sinuous/h/src/remove-nodes' {
  declare module.exports: any;
}

declare module 'sinuous/htm/src/build' {
  declare module.exports: any;
}

declare module 'sinuous/htm/src/constants-mini' {
  declare module.exports: any;
}

declare module 'sinuous/htm/src/constants' {
  declare module.exports: any;
}

declare module 'sinuous/htm/src' {
  declare module.exports: any;
}

declare module 'sinuous/hydrate/src/hydrate' {
  declare module.exports: any;
}

declare module 'sinuous/hydrate/src' {
  declare module.exports: any;
}

declare module 'sinuous/map/mini/src/mini' {
  declare module.exports: any;
}

declare module 'sinuous/map/mini/test/mini-basic' {
  declare module.exports: any;
}

declare module 'sinuous/map/mini/test/mini' {
  declare module.exports: any;
}

declare module 'sinuous/map/src/constants' {
  declare module.exports: any;
}

declare module 'sinuous/map/src' {
  declare module.exports: any;
}

declare module 'sinuous/map/src/map' {
  declare module.exports: any;
}

declare module 'sinuous/map/src/utils' {
  declare module.exports: any;
}

declare module 'sinuous/memo/src/memo' {
  declare module.exports: any;
}

declare module 'sinuous/module/all' {
  declare module.exports: any;
}

declare module 'sinuous/module/babel-plugin-htm' {
  declare module.exports: any;
}

declare module 'sinuous/module/data' {
  declare module.exports: any;
}

declare module 'sinuous/module/h' {
  declare module.exports: any;
}

declare module 'sinuous/module/htm' {
  declare module.exports: any;
}

declare module 'sinuous/module/hydrate' {
  declare module.exports: any;
}

declare module 'sinuous/module/map' {
  declare module.exports: any;
}

declare module 'sinuous/module/map/mini' {
  declare module.exports: any;
}

declare module 'sinuous/module/memo' {
  declare module.exports: any;
}

declare module 'sinuous/module/observable' {
  declare module.exports: any;
}

declare module 'sinuous/module/render' {
  declare module.exports: any;
}

declare module 'sinuous/module/sinuous-observable' {
  declare module.exports: any;
}

declare module 'sinuous/module/sinuous' {
  declare module.exports: any;
}

declare module 'sinuous/module/template' {
  declare module.exports: any;
}

declare module 'sinuous/observable/src/observable' {
  declare module.exports: any;
}

declare module 'sinuous/observable/src/utils' {
  declare module.exports: any;
}

declare module 'sinuous/render/src' {
  declare module.exports: any;
}

declare module 'sinuous/render/src/render' {
  declare module.exports: any;
}

declare module 'sinuous/src' {
  declare module.exports: any;
}

declare module 'sinuous/template/src/template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sinuous/all/src/all.js' {
  declare module.exports: $Exports<'sinuous/all/src/all'>;
}
declare module 'sinuous/all/src/index' {
  declare module.exports: $Exports<'sinuous/all/src'>;
}
declare module 'sinuous/all/src/index.js' {
  declare module.exports: $Exports<'sinuous/all/src'>;
}
declare module 'sinuous/babel-plugin-htm/src/index' {
  declare module.exports: $Exports<'sinuous/babel-plugin-htm/src'>;
}
declare module 'sinuous/babel-plugin-htm/src/index.js' {
  declare module.exports: $Exports<'sinuous/babel-plugin-htm/src'>;
}
declare module 'sinuous/data/src/data.js' {
  declare module.exports: $Exports<'sinuous/data/src/data'>;
}
declare module 'sinuous/dist/all.js' {
  declare module.exports: $Exports<'sinuous/dist/all'>;
}
declare module 'sinuous/dist/all.min.js' {
  declare module.exports: $Exports<'sinuous/dist/all.min'>;
}
declare module 'sinuous/dist/babel-plugin-htm.js' {
  declare module.exports: $Exports<'sinuous/dist/babel-plugin-htm'>;
}
declare module 'sinuous/dist/data.js' {
  declare module.exports: $Exports<'sinuous/dist/data'>;
}
declare module 'sinuous/dist/data.min.js' {
  declare module.exports: $Exports<'sinuous/dist/data.min'>;
}
declare module 'sinuous/dist/h.js' {
  declare module.exports: $Exports<'sinuous/dist/h'>;
}
declare module 'sinuous/dist/h.min.js' {
  declare module.exports: $Exports<'sinuous/dist/h.min'>;
}
declare module 'sinuous/dist/htm.js' {
  declare module.exports: $Exports<'sinuous/dist/htm'>;
}
declare module 'sinuous/dist/htm.min.js' {
  declare module.exports: $Exports<'sinuous/dist/htm.min'>;
}
declare module 'sinuous/dist/hydrate.js' {
  declare module.exports: $Exports<'sinuous/dist/hydrate'>;
}
declare module 'sinuous/dist/hydrate.min.js' {
  declare module.exports: $Exports<'sinuous/dist/hydrate.min'>;
}
declare module 'sinuous/dist/map.js' {
  declare module.exports: $Exports<'sinuous/dist/map'>;
}
declare module 'sinuous/dist/map.min.js' {
  declare module.exports: $Exports<'sinuous/dist/map.min'>;
}
declare module 'sinuous/dist/map/mini.js' {
  declare module.exports: $Exports<'sinuous/dist/map/mini'>;
}
declare module 'sinuous/dist/map/mini.min.js' {
  declare module.exports: $Exports<'sinuous/dist/map/mini.min'>;
}
declare module 'sinuous/dist/memo.js' {
  declare module.exports: $Exports<'sinuous/dist/memo'>;
}
declare module 'sinuous/dist/memo.min.js' {
  declare module.exports: $Exports<'sinuous/dist/memo.min'>;
}
declare module 'sinuous/dist/observable.js' {
  declare module.exports: $Exports<'sinuous/dist/observable'>;
}
declare module 'sinuous/dist/observable.min.js' {
  declare module.exports: $Exports<'sinuous/dist/observable.min'>;
}
declare module 'sinuous/dist/render.js' {
  declare module.exports: $Exports<'sinuous/dist/render'>;
}
declare module 'sinuous/dist/render.min.js' {
  declare module.exports: $Exports<'sinuous/dist/render.min'>;
}
declare module 'sinuous/dist/sinuous-observable.min.js' {
  declare module.exports: $Exports<'sinuous/dist/sinuous-observable.min'>;
}
declare module 'sinuous/dist/sinuous.js' {
  declare module.exports: $Exports<'sinuous/dist/sinuous'>;
}
declare module 'sinuous/dist/sinuous.min.js' {
  declare module.exports: $Exports<'sinuous/dist/sinuous.min'>;
}
declare module 'sinuous/dist/template.js' {
  declare module.exports: $Exports<'sinuous/dist/template'>;
}
declare module 'sinuous/dist/template.min.js' {
  declare module.exports: $Exports<'sinuous/dist/template.min'>;
}
declare module 'sinuous/h/src/add.js' {
  declare module.exports: $Exports<'sinuous/h/src/add'>;
}
declare module 'sinuous/h/src/api.js' {
  declare module.exports: $Exports<'sinuous/h/src/api'>;
}
declare module 'sinuous/h/src/cast-node.js' {
  declare module.exports: $Exports<'sinuous/h/src/cast-node'>;
}
declare module 'sinuous/h/src/constants.js' {
  declare module.exports: $Exports<'sinuous/h/src/constants'>;
}
declare module 'sinuous/h/src/frag.js' {
  declare module.exports: $Exports<'sinuous/h/src/frag'>;
}
declare module 'sinuous/h/src/h.js' {
  declare module.exports: $Exports<'sinuous/h/src/h'>;
}
declare module 'sinuous/h/src/index' {
  declare module.exports: $Exports<'sinuous/h/src'>;
}
declare module 'sinuous/h/src/index.js' {
  declare module.exports: $Exports<'sinuous/h/src'>;
}
declare module 'sinuous/h/src/insert.js' {
  declare module.exports: $Exports<'sinuous/h/src/insert'>;
}
declare module 'sinuous/h/src/property.js' {
  declare module.exports: $Exports<'sinuous/h/src/property'>;
}
declare module 'sinuous/h/src/remove-nodes.js' {
  declare module.exports: $Exports<'sinuous/h/src/remove-nodes'>;
}
declare module 'sinuous/htm/src/build.js' {
  declare module.exports: $Exports<'sinuous/htm/src/build'>;
}
declare module 'sinuous/htm/src/constants-mini.js' {
  declare module.exports: $Exports<'sinuous/htm/src/constants-mini'>;
}
declare module 'sinuous/htm/src/constants.js' {
  declare module.exports: $Exports<'sinuous/htm/src/constants'>;
}
declare module 'sinuous/htm/src/index' {
  declare module.exports: $Exports<'sinuous/htm/src'>;
}
declare module 'sinuous/htm/src/index.js' {
  declare module.exports: $Exports<'sinuous/htm/src'>;
}
declare module 'sinuous/hydrate/src/hydrate.js' {
  declare module.exports: $Exports<'sinuous/hydrate/src/hydrate'>;
}
declare module 'sinuous/hydrate/src/index' {
  declare module.exports: $Exports<'sinuous/hydrate/src'>;
}
declare module 'sinuous/hydrate/src/index.js' {
  declare module.exports: $Exports<'sinuous/hydrate/src'>;
}
declare module 'sinuous/map/mini/src/mini.js' {
  declare module.exports: $Exports<'sinuous/map/mini/src/mini'>;
}
declare module 'sinuous/map/mini/test/mini-basic.js' {
  declare module.exports: $Exports<'sinuous/map/mini/test/mini-basic'>;
}
declare module 'sinuous/map/mini/test/mini.js' {
  declare module.exports: $Exports<'sinuous/map/mini/test/mini'>;
}
declare module 'sinuous/map/src/constants.js' {
  declare module.exports: $Exports<'sinuous/map/src/constants'>;
}
declare module 'sinuous/map/src/index' {
  declare module.exports: $Exports<'sinuous/map/src'>;
}
declare module 'sinuous/map/src/index.js' {
  declare module.exports: $Exports<'sinuous/map/src'>;
}
declare module 'sinuous/map/src/map.js' {
  declare module.exports: $Exports<'sinuous/map/src/map'>;
}
declare module 'sinuous/map/src/utils.js' {
  declare module.exports: $Exports<'sinuous/map/src/utils'>;
}
declare module 'sinuous/memo/src/memo.js' {
  declare module.exports: $Exports<'sinuous/memo/src/memo'>;
}
declare module 'sinuous/module/all.js' {
  declare module.exports: $Exports<'sinuous/module/all'>;
}
declare module 'sinuous/module/babel-plugin-htm.js' {
  declare module.exports: $Exports<'sinuous/module/babel-plugin-htm'>;
}
declare module 'sinuous/module/data.js' {
  declare module.exports: $Exports<'sinuous/module/data'>;
}
declare module 'sinuous/module/h.js' {
  declare module.exports: $Exports<'sinuous/module/h'>;
}
declare module 'sinuous/module/htm.js' {
  declare module.exports: $Exports<'sinuous/module/htm'>;
}
declare module 'sinuous/module/hydrate.js' {
  declare module.exports: $Exports<'sinuous/module/hydrate'>;
}
declare module 'sinuous/module/map.js' {
  declare module.exports: $Exports<'sinuous/module/map'>;
}
declare module 'sinuous/module/map/mini.js' {
  declare module.exports: $Exports<'sinuous/module/map/mini'>;
}
declare module 'sinuous/module/memo.js' {
  declare module.exports: $Exports<'sinuous/module/memo'>;
}
declare module 'sinuous/module/observable.js' {
  declare module.exports: $Exports<'sinuous/module/observable'>;
}
declare module 'sinuous/module/render.js' {
  declare module.exports: $Exports<'sinuous/module/render'>;
}
declare module 'sinuous/module/sinuous-observable.js' {
  declare module.exports: $Exports<'sinuous/module/sinuous-observable'>;
}
declare module 'sinuous/module/sinuous.js' {
  declare module.exports: $Exports<'sinuous/module/sinuous'>;
}
declare module 'sinuous/module/template.js' {
  declare module.exports: $Exports<'sinuous/module/template'>;
}
declare module 'sinuous/observable/src/observable.js' {
  declare module.exports: $Exports<'sinuous/observable/src/observable'>;
}
declare module 'sinuous/observable/src/utils.js' {
  declare module.exports: $Exports<'sinuous/observable/src/utils'>;
}
declare module 'sinuous/render/src/index' {
  declare module.exports: $Exports<'sinuous/render/src'>;
}
declare module 'sinuous/render/src/index.js' {
  declare module.exports: $Exports<'sinuous/render/src'>;
}
declare module 'sinuous/render/src/render.js' {
  declare module.exports: $Exports<'sinuous/render/src/render'>;
}
declare module 'sinuous/src/index' {
  declare module.exports: $Exports<'sinuous/src'>;
}
declare module 'sinuous/src/index.js' {
  declare module.exports: $Exports<'sinuous/src'>;
}
declare module 'sinuous/template/src/template.js' {
  declare module.exports: $Exports<'sinuous/template/src/template'>;
}
